name: Generate Pink Contribution Snake

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Generate Pink Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sankuuX07
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23FF1493&color_dots=%230D1117,%233D0A2E,%237A124F,%23C21875,%23FF69B4
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FF1493&color_dots=%230D1117,%233D0A2E,%237A124F,%23C21875,%23FF69B4

      - name: Push Pink Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
